#ifndef ASTC_TRANSCODER_VERSION_H
#define ASTC_TRANSCODER_VERSION_H


#define ASTC_TRANSCODER_VERSION_MAJOR       1
#define ASTC_TRANSCODER_VERSION_MINOR       0
#define ASTC_TRANSCODER_VERSION_RELEASE     1
#define ASTC_TRANSCODER_VERSION_BUILD       0


#endif // ASTC_TRANSCODER_VERSION_H
